name: CI Workflow

on:
  push:
    branches:
      - main
      - rahi # Add any branches you want to trigger on push
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db: # Example if you need a database service
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build . -t myapp:latest

      - name: Run Docker container
        run: |
          docker run -d --name myapp_container -p 5000:5000 myapp:latest # Run in detached mode

      - name: Wait for the application to be ready
        run: |
          for i in {1..30}; do # Wait for the app to be ready
            curl -f http://localhost:5000/ && break || sleep 5;
          done

      - name: Run tests
        run: |
          docker exec myapp_container python -m unittest discover  # Adjust this based on your test structure

      - name: Stop and remove container
        run: docker stop myapp_container && docker rm myapp_container
